import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us | CampaignFlow",
  description: "Learn more about CampaignFlow, our mission, and our editorial policies.",
};

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 max-w-4xl py-16 md:py-24">
      <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-8">About CampaignFlow</h1>
      
      <article className="prose prose-zinc dark:prose-invert lg:prose-lg max-w-none">
        <p className="lead">
          CampaignFlow was created with a simple mission: to provide high-quality, actionable, and deeply researched content that empowers individuals to build, grow, and succeed in the digital world.
        </p>

        <h2>Our Mission</h2>
        <p>
          In a world overflowing with information, finding reliable and structured guidance can be overwhelming. We aim to cut through the noise by delivering curated campaigns and comprehensive guides that take you from beginner to expert, step by step.
        </p>

        <h2>Content Policy</h2>
        <p>
          We pride ourselves on editorial integrity. All our articles are researched and written by industry professionals. We do not publish autogenerated spam, and we rigorously fact-check our technical guides to ensure they reflect the latest best practices.
        </p>
        
        <h2>Why We Do It</h2>
        <ul>
          <li><strong>Education Should Be Accessible:</strong> We believe high-quality knowledge shouldn't be locked behind expensive paywalls.</li>
          <li><strong>Action Over Theory:</strong> Our content focuses on practical application rather than abstract concepts.</li>
          <li><strong>Continuous Learning:</strong> Technology moves fast, and we are dedicated to helping our readers stay ahead of the curve.</li>
        </ul>
      </article>
    </div>
  );
}
